export const adminLoggingConstant = {
    USER_LOG_FETCH_START: 'USER-LOG-FETCH-START',
    USER_LOG_FETCH_SUCCESS: 'USER-LOG-FETCH-SUCCESS',
    USER_LOG_FETCH_ERROR: 'USER-LOG-FETCH-ERROR',
    USER_LOG_STATS_FETCH_START: 'USER-LOG-STATS-FETCH-START',
    USER_LOG_STATS_FETCH_SUCCESS: 'USER-LOG-STATS-FETCH-SUCCESS',
    USER_LOG_STATS_FETCH_ERROR: 'USER-LOG-STATS-FETCH-ERROR',
    USER_LOG_DIAGRAM_FETCH_START: 'USER-LOG-DIAGRAM-FETCH-START',
    USER_LOG_DIAGRAM_FETCH_SUCCESS: 'USER-LOG-DIAGRAM-FETCH-SUCCESS',
    USER_LOG_DIAGRAM_FETCH_ERROR: 'USER-LOG-DIAGRAM-FETCH-ERROR'
};
