export const appointmentDetailsConstants = {
    REFUND_FETCH_START: 'REFUND-FETCH-START',
    REFUND_FETCH_SUCCESS: 'REFUND-FETCH-SUCCESS',
    REFUND_FETCH_ERROR: 'REFUND-FETCH-ERROR',
    CLEAR_REFUND_LIST_MESSAGE:'CLEAR-REFUND-LIST-MESSAGE'
   };
