export const loginActionConstant = {
  PENDING: 'LOGIN_PENDING',
  SUCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR'
}

export const userMenusActionConstant = {
  PENDING: 'MENU_PENDING',
  SUCESS: 'MENU_SUCCESS',
  ERROR: 'MENU_ERROR'
}

export const loggedInAdminInfoActionConstants = {
  PENDING: 'ADMIN_INFO_FETCH_PENDING',
  SUCCESS: 'ADMIN_INFO_FETCH_SUCCESS',
  ERROR: 'ADMIN_INFO_FETCH_ERROR'
}

export const logoutActionConstants = {
  PENDING: 'LOGOUT_PENDING',
  SUCCESS: 'LOGOUT_SUCCESS',
  ERROR: 'LOGOUT_ERROR',
  CLEAR_ERROR_MESSAGE: 'CLEAR_LOGOUT_ERROR_MESSAGE'
}

export const forgotPasswordAndVerificationConstants = {
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',
  FORGOT_PASSWORD_PENDING: 'FORGOT_PASSWORD_PENDING',
  PASSWORD_VERIFICATION_SUCCESS: 'PASSWORD_VERIFICATION_SUCCESS',
  PASSWORD_VERIFICATION_ERROR: 'PASSWORD_VERIFICATION_ERROR',
  PASSWORD_VERIFICATION_PENDING: 'PASSWORD_VERIFICATION_PENDING',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',
  CHANGE_PASSWORD_PENDING: 'CHANGE_PASSWORD_PENDING',
}
