export const salutationActionConstants = {
    FETCH_SALUTATION_PENDING: 'FETCH_SALUTATION_PENDING',
    FETCH_SALUTATION_SUCCESS: 'FETCH_SALUTATION_SUCCESS',
    FETCH_SALUTATION_ERROR: 'FETCH_SALUTATION_ERROR',
}
