export const apiIntegrationFeatureTypeCodes = {
    APPOINTMENT_CHECK_IN_CODE: "DOC_APPCH",
    DEPARTMENT_CHECK_IN_CODE:"DEP_APPCH",
    APPOINTMENT_REFUND_APPROVAL_CODE: "REFUND",
    APPOINTMENT_REFUND_STATUS_CODE:"PAYMENT_STATUS"
}


export const apiIntegrationKey = {
    CLIENT_FEATURE_INTEGRATION: "e-c-integrate",
    APPOINTMENT_MODE_FEATURE_INTEGRATION: 'e-a-integrate',
    ALL_CLIENT_FEATURE_INTEGRATION: "e-c-allIntegrate",
    ALL_APPOINTMENT_MODE_FEATURE_INTEGRATION: 'e-a-allIntegrate',
}
