export const minioFileLocationConstants = {
    CLIENT_FILE_LOCATION: process.env.REACT_APP_CLIENT_PUBLIC_FILE_UPLOAD_LOCATION,
    COMPANY_FILE_LOCATION: process.env.REACT_APP_COMPANY_PUBLIC_FILE_UPLOAD_LOCATION
}
