export const minioFileLocationConstants = {
    CLIENT_PUBLIC_FILE_LOCATION: process.env.REACT_APP_CLIENT_PUBLIC_FILE_UPLOAD_LOCATION,
    COMPANY_PUBLIC_FILE_LOCATION: process.env.REACT_APP_COMPANY_PUBLIC_FILE_UPLOAD_LOCATION,
    CLIENT_PRIVATE_FILE_LOCATION: process.env.REACT_APP_CLIENT_PRIVATE_FILE_UPLOAD_LOCATION,
    COMPANY_PRIVATE_FILE_LOCATION: process.env.REACT_APP_COMPANY_PRIVATE_FILE_UPLOAD_LOCATION
}
