export const dashboardDetailsActionsConstant = {
  DASHBOARD_REVENUE_DAY_FETCH_START: 'DASHBOARD_REVENUE_DAY_FETCH_START',
  DASHBOARD_REVENUE_DAY_FETCH_SUCCESS: 'DASHBOARD_REVENUE_DAY_FETCH_SUCCESS',
  DASHBOARD_REVENUE_DAY_FETCH_ERROR: 'DASHBOARD_REVENUE_DAY_FETCH_ERROR',
  DASHBOARD_REVENUE_MONTH_FETCH_START: 'DASHBOARD_REVENUE_MONTH_FETCH_START',
  DASHBOARD_REVENUE_MONTH_FETCH_SUCCESS:
    'DASHBOARD_REVENUE_MONTH_FETCH_SUCCESS',
  DASHBOARD_REVENUE_MONTH_FETCH_ERROR: 'DASHBOARD_REVENUE_MONTH_FETCH_ERROR',
  DASHBOARD_REVENUE_WEEK_FETCH_START: 'DASHBOARD_REVENUE_WEEK_FETCH_START',
  DASHBOARD_REVENUE_WEEK_FETCH_SUCCESS: 'DASHBOARD_REVENUE_WEEK_FETCH_SUCCESS',
  DASHBOARD_REVENUE_WEEK_FETCH_ERROR: 'DASHBOARD_REVENUE_WEEK_FETCH_ERROR',
  DASHBOARD_REVENUE_YEAR_FETCH_START: 'DASHBOARD_REVENUE_YEAR_FETCH_START',
  DASHBOARD_REVENUE_YEAR_FETCH_SUCCESS: 'DASHBOARD_REVENUE_YEAR_FETCH_SUCCESS',
  DASHBOARD_REVENUE_YEAR_FETCH_ERROR: 'DASHBOARD_REVENUE_YEAR_FETCH_ERROR',
  DASHBOARD_REGISTERED_PATIENTS_FETCH_START:
    'DASHBOARD_REGISTERED_PATIENTS_FETCH_START',
  DASHBOARD_REGISTERED_PATIENTS_FETCH_SUCCESS:
    'DASHBOARD_REGISTERED_PATIENTS_FETCH_SUCCESS',
  DASHBOARD_REGISTERED_PATIENTS_FETCH_ERROR:
    'DASHBOARD_REGISTERED_PATIENTS_FETCH_ERROR',
  DASHBOARD_APPOINTMENT_STATISTICS_START:
    'DASHBOARD_APPOINTMENT_STATISTICS_START',
  DASHBOARD_APPOINTMENT_STATISTICS_SUCCESS:
    'DASHBOARD_APPOINTMENT_STATISTICS_SUCCESS',
  DASHBOARD_APPOINTMENT_STATISTICS_ERROR:
    'DASHBOARD_APPOINTMENT_STATISTICS_FETCH_ERROR',
  DASHBOARD_REVENUE_STATISTICS_FETCH_START:
    'DASHBOARD_REVENUE_STATISTICS_FETCH_START',
  DASHBOARD_REVENUE_STATISTICS_FETCH_SUCCESS:
    'DASHBOARD_REVENUE_STATISTICS_FETCH_SUCCESS',
  DASHBOARD_REVENUE_STATISTICS_FETCH_ERROR:
    'DASHBOARD_REVENUE_STATISTICS_FETCH_ERROR',
  DASHBOARD_APPOINTMENT_QUEUE_FETCH_START:
    'DASHBOARD_APPOINTMENT_QUEUE_FETCH_START',
  DASHBOARD_APPOINTMENT_QUEUE_FETCH_SUCCESS:
    'DASHBOARD_APPOINTMENT_QUEUE_FETCH_SUCCESS',
  DASHBOARD_APPOINTMENT_QUEUE_FETCH_ERROR:
    'DASHBOARD_APPOINTMENT_QUEUE_FETCH_ERROR',
  DASHBOARD_DOCTOR_REVENUE_FETCH_START: 'DASHBOARD_DOCTOR_REVENUE_FETCH_START',
  DASHBOARD_DOCTOR_REVENUE_FETCH_SUCCESS:
    'DASHBOARD_DOCTOR_REVENUE_FETCH_SUCCESS',
  DASHBOARD_DOCTOR_REVENUE_FETCH_ERROR: 'DASHBOARD_DOCTOR_REVENUE_FETCH_ERROR',
  CLEAR_DASHBOARD_DOCTOR_REVENUE_MESSAGE:
    'CLEAR_DASHBOARD_DOCTOR_REVENUE_MESSAGE',
  FETCH_DASHBOARD_FEATURES_START: 'FETCH_DASHBOARD_FEATURES_START',
  FETCH_DASHBOARD_FEATURES_SUCCESS: 'FETCH_DASHBOARD_FEATURES_SUCCESS',
  FETCH_DASHBOARD_FEATURES_ERROR: 'FETCH_DASHBOARD_FEATURES_PENDING',
  FETCH_DASHBOARD_FEATURES_BY_ADMIN_ID_ERROR:
    'FETCH_DASHBOARD_FEATURES_BY_ADMIN_ID_ERROR',
  FETCH_DASHBOARD_FEATURES_BY_ADMIN_ID_SUCCESS:
    'FETCH_DASHBOARD_FEATURES_BY_ADMIN_ID_SUCCESS',
  FETCH_DASHBOARD_FEATURES_BY_ADMIN_ID_PENDING:
    'FETCH_DASHBOARD_FEATURES_BY_ADMIN_ID_PENDING',
  FETCH_DASHBOARD_DEPARMENT_REVENUE_ERROR:
    'FETCH_DASHBOARD_DEPARMENT_REVENUE_ERROR',
  FETCH_DASHBOARD_DEPARMENT_REVENUE_SUCCESS:
    'FETCH_DASHBOARD_DEPARMENT_REVENUE_SUCCESS',
  FETCH_DASHBOARD_DEPARMENT_REVENUE_PENDING:
    ' FETCH_DASHBOARD_DEPARMENT_REVENUE_PENDING',
  CLEAR_DASHBOARD_DEPARTMENT_REVENUE_MESSAGE:'CLEAR_DASHBOARD_DEPARTMENT_REVENUE_MESSAGE'
}
