export const excludedUrl = [
    '/search',
    '/active/min',
    '/login',
    '/sidebar',
    '/info',
    '/metaInfo',
    '/hospital-wise',
    '/doctor-wise',
    '/specialization-wise',
    '/forgot',
    '/verify',
    '/dropdown',
    '/doctorDutyRosterOverride',
    '/existing',
    '/weekDays',
    '/dashboard',
    '/detail',
    '/country',
    '/updateDetails',
    '/min',
    '/adminFeature',
    '/profile/',
    '/department/',
]
export const includeAppUrl=[
    '/approve/',
    '/reject/',
    
]