export const appointmentServiceTypeActionConstants = {
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_PENDING: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-PENDING',
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_SUCCESS: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-SUCCESS',
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_ERROR: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-ERROR',
};
