export const appointmentServiceTypeActionConstants = {
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_PENDING: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-PENDING',
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_SUCCESS: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-SUCCESS',
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_ERROR: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-ERROR',
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_WITH_CODE_PENDING: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-WITH-CODE-PENDING',
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_WITH_CODE_SUCCESS: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-WITH-CODE-SUCCESS',
    FETCH_ACTIVE_APPOINTMENT_SERVICE_TYPE_FOR_DROPDOWN_WITH_CODE_ERROR: 'FETCH-ACTIVE-APPOINTMENT-SERVICE-TYPE-FOR-DROPDOWN-WITH-CODE-ERROR',
};
