export const hospitalApiIntegrationActionConstants = {
    HOSPITAL_API_SAVE_SUCCESS:'HOSPITAL_API_SAVE_SUCCESS',
    HOSPITAL_API_SAVE_ERROR:'HOSPITAL_API_SAVE_ERROR',
    HOSPITAL_API_SAVE_PENDING:'HOSPITAL_API_SAVE_PENDING',
    HOSPITAL_REQUEST_METHOD_DROPDOWN_SUCCESS:'HOSPITAL_REQUEST_METHOD_DROPDOWN_SUCCESS',
    HOSPITAL_REQUEST_METHOD_DROPDOWN_ERROR:'HOSPITAL_REQUEST_METHOD_DROPDOWN_ERROR',
    HOSPITAL_REQUEST_METHOD_DROPDOWN_PENDING:'HOSPITAL_REQUEST_METHOD_DROPDOWN_PENDING',
    HOSPTIAL_FEATURE_TYPE_DROPDOWN_SUCCESS:'HOSPITAL_FEATURE_TYPE_DROPDOWN_SUCCESS',
    HOSPTIAL_FEATURE_TYPE_DROPDOWN_ERROR:'HOSPITAL_FEATURE_TYPE_DROPDOWN_ERROR',
    HOSPTIAL_FEATURE_TYPE_DROPDOWN_PENDING:'HOSPITAL_FEATURE_TYPE_DROPDOWN_PENDING',
}