export const doctorSalutationActionConstants = {
    FETCH_DOCTOR_SALUTATION_PENDING: 'FETCH_DOCTOR_SALUTATION_PENDING',
    FETCH_DOCTOR_SALUTATION_SUCCESS: 'FETCH_DOCTOR_SALUTATION_SUCCESS',
    FETCH_DOCTOR_SALUTATION_ERROR: 'FETCH_DOCTOR_SALUTATION_ERROR',
}
