export const favouritesActionConstants = {
    SAVE_FAVOURITES_PENDING: "SAVE-FAVOURITES-PENDING",
    SAVE_FAVOURITES_SUCCESS: "SAVE-FAVOURITES-SUCCESS",
    SAVE_FAVOURITES_ERROR: "SAVE-FAVOURITES-ERROR",
    UPDATE_FAVOURITES_PENDING: "UPDATE-FAVOURITES-PENDING",
    UPDATE_FAVOURITES_SUCCESS: "UPDATE-FAVOURITES-SUCCESS",
    UPDATE_FAVOURITES_ERROR: "UPDATE-FAVOURITES-ERROR",
    FETCH_FAVOURITES_FOR_DROPDOWN_PENDING: "FETCH-FAVOURITES-FOR-DROPDOWN-PENDING",
    FETCH_FAVOURITES_FOR_DROPDOWN_SUCCESS: "FETCH-FAVOURITES-FOR-DROPDOWN-SUCCESS",
    FETCH_FAVOURITES_FOR_DROPDOWN_ERROR: "FETCH-FAVOURITES-FOR-DROPDOWN-ERROR",
}
