export const appointmentTransferConstant = {
  APPOINTMENT_TRANSFER_SUCCESS: 'APPOINTMENT_TRANSFER_SUCCESS',
  APPOINTMENT_TRANSFER_PENDING: 'APPOINTMENT_TRANSFER_PENDING',
  APPOINTMENT_TRANSFER_ERROR: 'APPOINTMENT_TRANSFER_ERROR',
  APPOINTMENT_TRANSFER_DATE_SUCCESS: 'APPOINTMENT_TRANSFER_DATE_SUCCESS',
  APPOINTMENT_TRANSFER_DATE_PENDING: 'APPOINTMENT_TRANSFER_DATE_PENDING',
  APPOINTMENT_TRANSFER_DATE_ERROR: 'APPOINTMENT_TRANSFER_DATE_ERROR',
  APPOINTMENT_TRANSFER_TIME_SUCCESS: 'APPOINTMENT_TRANSFER_TIME_SUCCESS',
  APPOINTMENT_TRANSFER_TIME_PENDING: 'APPOINTMENT_TRANSFER_TIME_PENDING',
  APPOINTMENT_TRANSFER_TIME_ERROR: 'APPOINTMENT_TRANSFER_TIME_ERROR',
  APPOINTMENT_TRANSFER_INFO_SUCCESS: 'APPOINTMENT_TRANSFER_INFO_SUCCESS',
  APPOINTMENT_TRANSFER_INFO_PENDING: 'APPOINTMENT_TRANSFER_INFO_PENDING',
  APPOINTMENT_TRANSFER_INFO_ERROR: 'APPOINTMENT_TRANSFER_INFO_ERROR',
  APPOINTMENT_TRANSFER_CHARGE_SUCCESS: 'APPOINTMENT_TRANSFER_CHARGE_SUCCESS',
  APPOINTMENT_TRANSFER_CHARGE_PENDING: ' APPOINTMENT_TRANSFER_CHARGE_PENDING',
  APPOINTMENT_TRANSFER_CHARGE_ERROR: ' APPOINTMENT_TRANSFER_CHARGE_ERROR'
};
