export const adminModeApiIntegrationActionConstants = {
  ADMIN_MODE_API_INTEGRATION_SAVE_SUCCESS: 'ADMIN_MODE_API_INTEGRATION_SAVE_SUCCESS',
  ADMIN_MODE_API_INTEGRATION_SAVE_ERROR: 'ADMIN_MODE_INTEGRATION_API_SAVE_ERROR',
  ADMIN_MODE_API_INTEGRATION_SAVE_PENDING: 'ADMIN_MODE_API_INTEGRATION_SAVE_PENDING',
  ADMIN_MODE_API_INTEGRATION_SEARCH_SUCCESS:
    'ADMIN_MODE_API_INTEGRATION_SEARCH_SUCCESS',
  ADMIN_MODE_API_INTEGRATION_SEARCH_ERROR:
    'ADMIN_MODE_API_INTEGRATION_SEARCH_ERROR',
  ADMIN_MODE_API_INTEGRATION_SEARCH_PENDING:
    'ADMIN_MODE_API_INTEGRATION_SEARCH_PENDING',
  ADMIN_MODE_API_INTEGRATION_PREVIEW_PENDING:
    'ADMIN_MODE_API_INTEGRATION_PREVIEW_PENDIN',
  ADMIN_MODE_API_INTEGRATION_PREVIEW_SUCCESS:
    'ADMIN_MODE_API_INTEGRATION_PREVIEW_SUCCESS',
  ADMIN_MODE_API_INTEGRATION_PREVIEW_ERROR:
    'ADMIN_MODE_API_INTEGRATION_PREVIEW_ERROR',
  ADMIN_MODE_API_INTEGRATION_EDIT_PENDING:
    'ADMIN_MODE_API_INTEGRATION_EDIT_PENDING',
  ADMIN_MODE_API_INTEGRATION_EDIT_ERROR: 'ADMIN_MODE_API_INTEGRATION_EDIT_ERROR',
  ADMIN_MODE_API_INTEGRATION_EDIT_SUCCESS:
    'ADMIN_MODE_API_INTEGRATION_EDIT_SUCCESS',
  ADMIN_MODE_API_INTEGRATION_DELETE_PENDING:
    'ADMIN_MODE_API_INTEGRATION_DELETE_PENDING',
  ADMIN_MODE_API_INTEGRATION_DELETE_ERROR:
    'ADMIN_MODE_API_INTEGRATION_DELETE_ERROR',
  ADMIN_MODE_API_INTEGRATION_DELETE_SUCCESS:
    'ADMIN_MODE_API_INTEGRATION_DELETE_SUCCESS',
  CLEAR_ADMIN_MODE_API_DELETE_MESSAGE: 'CLEAR_ADMIN_MODE_API_DELETE_MESSAGE',
  CLEAR_ADMIN_MODE_API_PREVIEW_MESSAGE: 'CLEAR_ADMIN_MODE_API_PREVIEW_MESSAGE',
  CLEAR_ADMIN_MODE_API_EDIT_MESSAGE: 'CLEAR_ADMIN_MODE_API_EDIT_MESSAGE',
  ADMIN_API_APPOINTMENT_MODE_DROPDOWN_PENDING:'ADMIN_API_APPOINTMENT_MODE_DROPDOWN_PENDING',
  ADMIN_API_APPOINTMENT_MODE_DROPDOWN_SUCCESS:'ADMIN_API_APPOINTMENT_MODE_DROPDOWN_SUCCESS',
  ADMIN_API_APPOINTMENT_MODE_DROPDOWN_ERROR:'ADMIN_API_APPOINTMENT_MODE_DROPDOWN_ERROR',
}
