export const patientDetailsConstants = {
    PATIENT_ACTIVE_DROPDOWN_META_FETCH_START: 'PATIENT_ACTIVE_DROPDOWN_META_FETCH_START',
    PATIENT_ACTIVE_DROPDOWN_META_FETCH_SUCCESS: 'PATIENT_ACTIVE_DROPDOWN_META_FETCH_SUCCESS',
    PATIENT_ACTIVE_DROPDOWN_META_FETCH_ERROR: 'PATIENT_ACTIVE_DROPDOWN_META_FETCH_SUCCESS',
    PATIENT_CLEAR_DROPDOWN_META:'CLEAR-REFUND-LIST-MESSAGE'
   };
