export const departmentDutyRosterActionConstants = {
    CREATE_DEPARTMENT_DUTY_ROSTER_PENDING: 'CREATE-DEPARTMENT-DUTY-ROSTER-PENDING',
    CREATE_DEPARTMENT_DUTY_ROSTER_SUCCESS: 'CREATE-DEPARTMENT-DUTY-ROSTER-SUCCESS',
    CREATE_DEPARTMENT_DUTY_ROSTER_ERROR: 'CREATE-DEPARTMENT-DUTY-ROSTER-ERROR',
    CLEAR_DEPARTMENT_DUTY_ROSTER_CREATE_MESSAGE: 'CLEAR-DEPARTMENT-DUTY-ROSTER-CREATE-MESSAGE',

    UPDATE_DEPARTMENT_DUTY_ROSTER_PENDING: 'UPDATE-DEPARTMENT-DUTY-ROSTER-PENDING',
    UPDATE_DEPARTMENT_DUTY_ROSTER_SUCCESS: 'UPDATE-DEPARTMENT-DUTY-ROSTER-SUCCESS',
    UPDATE_DEPARTMENT_DUTY_ROSTER_ERROR: 'UPDATE-DEPARTMENT-DUTY-ROSTER-ERROR',
    CLEAR_DEPARTMENT_DUTY_ROSTER_UPDATE_MESSAGE: 'CLEAR-DEPARTMENT-DUTY-ROSTER-UPDATE-MESSAGE',

    DELETE_DEPARTMENT_DUTY_ROSTER_PENDING: 'DELETE-DEPARTMENT-DUTY-ROSTER-PENDING',
    DELETE_DEPARTMENT_DUTY_ROSTER_SUCCESS: 'DELETE-DEPARTMENT-DUTY-ROSTER-SUCCESS',
    DELETE_DEPARTMENT_DUTY_ROSTER_ERROR: 'DELETE-DEPARTMENT-DUTY-ROSTER-ERROR',
    CLEAR_DEPARTMENT_DUTY_ROSTER_DELETE_MESSAGE: 'CLEAR-DEPARTMENT-DUTY-ROSTER-DELETE-MESSAGE',

    FETCH_DEPARTMENT_DUTY_ROSTER_DETAIL_PENDING: 'FETCH-DEPARTMENT-DUTY-ROSTER-DETAIL-PENDING',
    FETCH_DEPARTMENT_DUTY_ROSTER_DETAIL_SUCCESS: 'FETCH-DEPARTMENT-DUTY-ROSTER-DETAIL-SUCCESS',
    FETCH_DEPARTMENT_DUTY_ROSTER_DETAIL_ERROR: 'FETCH-DEPARTMENT-DUTY-ROSTER-DETAIL-ERROR',
    CLEAR_DEPARTMENT_DUTY_ROSTER_DETAIL_MESSAGE: 'CLEAR-DEPARTMENT-DUTY-ROSTER-DETAIL-MESSAGE',

    SEARCH_DEPARTMENT_DUTY_ROSTER_PENDING: 'SEARCH-DEPARTMENT-DUTY-ROSTER-PENDING',
    SEARCH_DEPARTMENT_DUTY_ROSTER_SUCCESS: 'SEARCH-DEPARTMENT-DUTY-ROSTER-SUCCESS',
    SEARCH_DEPARTMENT_DUTY_ROSTER_ERROR: 'SEARCH-DEPARTMENT-DUTY-ROSTER-ERROR',
    CLEAR_DEPARTMENT_DUTY_ROSTER_SEARCH_MESSAGE: 'CLEAR-DEPARTMENT-DUTY-ROSTER-SEARCH-MESSAGE',

    FETCH_EXISTING_DEPARTMENT_DUTY_ROSTER_PENDING: 'FETCH-EXISTING-DEPARTMENT-DUTY-ROSTER-PENDING',
    FETCH_EXISTING_DEPARTMENT_DUTY_ROSTER_SUCCESS: 'FETCH-EXISTING-DEPARTMENT-DUTY-ROSTER-SUCCESS',
    FETCH_EXISTING_DEPARTMENT_DUTY_ROSTER_ERROR: 'FETCH-EXISTING-DEPARTMENT-DUTY-ROSTER-ERROR',
    CLEAR_EXISTING_DEPARTMENT_DUTY_ROSTER_MESSAGE: 'CLEAR-EXISTING-DEPARTMENT-DUTY-ROSTER-MESSAGE',

    FETCH_EXISTING_DEPARTMENT_DUTY_ROSTER_DETAIL_BY_ID_PENDING: 'FETCH-EXISTING-DEPARTMENT-DUTY-ROSTER-DETAIL-BY-ID-PENDING',
    FETCH_EXISTING_DEPARTMENT_DUTY_ROSTER_DETAIL_BY_ID_SUCCESS: 'FETCH-EXISTING-DEPARTMENT-DUTY-ROSTER-DETAIL-BY-ID-SUCCESS',
    FETCH_EXISTING_DEPARTMENT_DUTY_ROSTER_DETAIL_BY_ID_ERROR: 'FETCH-EXISTING-DEPARTMENT-DUTY-ROSTER-DETAIL-BY-ID-ERROR',
    CLEAR_EXISTING_DEPARTMENT_DUTY_ROSTER_DETAIL_BY_ID_MESSAGE: 'CLEAR-EXISTING-DEPARTMENT-DUTY-ROSTER-DETAIL-BY-ID-MESSAGE',

    UPDATE_DEPARTMENT_DUTY_ROSTER_OVERRIDE_PENDING: 'UPDATE-DEPARTMENT-DUTY-ROSTER-OVERRIDE-PENDING',
    UPDATE_DEPARTMENT_DUTY_ROSTER_OVERRIDE_SUCCESS: 'UPDATE-DEPARTMENT-DUTY-ROSTER-OVERRIDE-SUCCESS',
    UPDATE_DEPARTMENT_DUTY_ROSTER_OVERRIDE_ERROR: 'UPDATE-DEPARTMENT-DUTY-ROSTER-OVERRIDE-ERROR',
    CLEAR_DEPARTMENT_DUTY_ROSTER_OVERRIDE_UPDATE_MESSAGE: 'CLEAR-DEPARTMENT-DUTY-ROSTER-OVERRIDE-UPDATE-MESSAGE',

    DELETE_DEPARTMENT_DUTY_ROSTER_OVERRIDE_PENDING: 'DELETE-DEPARTMENT-DUTY-ROSTER-OVERRIDE-PENDING',
    DELETE_DEPARTMENT_DUTY_ROSTER_OVERRIDE_SUCCESS: 'DELETE-DEPARTMENT-DUTY-ROSTER-OVERRIDE-SUCCESS',
    DELETE_DEPARTMENT_DUTY_ROSTER_OVERRIDE_ERROR: 'DELETE-DEPARTMENT-DUTY-ROSTER-OVERRIDE-ERROR',
    CLEAR_DEPARTMENT_DUTY_ROSTER_OVERRIDE_DELETE_MESSAGE: 'CLEAR-DEPARTMENT-DUTY-ROSTER-OVERRIDE-DELETE-MESSAGE',

    REVERT_DEPARTMENT_DUTY_ROSTER_OVERRIDE_PENDING: 'REVERT-DEPARTMENT-DUTY-ROSTER-OVERRIDE-PENDING',
    REVERT_DEPARTMENT_DUTY_ROSTER_OVERRIDE_SUCCESS: 'REVERT-DEPARTMENT-DUTY-ROSTER-OVERRIDE-SUCCESS',
    REVERT_DEPARTMENT_DUTY_ROSTER_OVERRIDE_ERROR: 'REVERT-DEPARTMENT-DUTY-ROSTER-OVERRIDE-ERROR',
    CLEAR_DEPARTMENT_DUTY_ROSTER_OVERRIDE_REVERT_MESSAGE: 'CLEAR-DEPARTMENT-DUTY-ROSTER-OVERRIDE-REVERT-MESSAGE'
};
