import {
    loggedInAdminInfoActionConstants,
    LoggedInAdminInfoActions,
    loginActionConstant,
    LoginActions,
    logoutActionConstants,
    LogoutActions,
    MenuActions,
    userMenusActionConstant,
    weekdaysActionConstants,
    WeekdaysActions
} from './src/common'
import {
    adminSetupActionConstants,
    AdminSetupActions,
    DoctorSetupActions,
    doctorSetupConstants,
    DepartmentSetupActions,
    departmentSetupConstants,
    doctorDutyRosterActionConstants,
    DoctorDutyRosterActions,
    HospitalSetupActions,
    hospitalSetupConstants,
    ProfileSetupActions,
    profileSetupConstants,
    SpecializationSetupActions,
    specializationSetupConstants,
} from './src/admin-module'

export {
    adminSetupActionConstants,
    AdminSetupActions,
    DoctorSetupActions,
    doctorSetupConstants,
    DepartmentSetupActions,
    departmentSetupConstants,
    doctorDutyRosterActionConstants,
    DoctorDutyRosterActions,
    HospitalSetupActions,
    hospitalSetupConstants,
    loginActionConstant,
    LoginActions,
    MenuActions,
    ProfileSetupActions,
    profileSetupConstants,
    SpecializationSetupActions,
    specializationSetupConstants,
    userMenusActionConstant,
    loggedInAdminInfoActionConstants,
    LoggedInAdminInfoActions,
    logoutActionConstants,
    LogoutActions,
    weekdaysActionConstants,
    WeekdaysActions
}
