import {
    loggedInAdminInfoActionConstants,
    LoggedInAdminInfoActions,
    loginActionConstant,
    LoginActions,
    logoutActionConstants,
    LogoutActions,
    MenuActions,
    userMenusActionConstant
} from './src/common'
import {
    adminSetupActionConstants,
    AdminSetupActions,
    ConsultantSetupActions,
    consultantSetupConstants,
    DepartmentSetupActions,
    departmentSetupConstants,
    HospitalSetupActions,
    hospitalSetupConstants,
    ProfileSetupActions,
    profileSetupConstants,
    SpecializationSetupActions,
    specializationSetupConstants,
} from './src/admin-module'

export {
    adminSetupActionConstants,
    AdminSetupActions,
    ConsultantSetupActions,
    consultantSetupConstants,
    DepartmentSetupActions,
    departmentSetupConstants,
    HospitalSetupActions,
    hospitalSetupConstants,
    loginActionConstant,
    LoginActions,
    MenuActions,
    ProfileSetupActions,
    profileSetupConstants,
    SpecializationSetupActions,
    specializationSetupConstants,
    userMenusActionConstant,
    loggedInAdminInfoActionConstants,
    LoggedInAdminInfoActions,
    logoutActionConstants,
    LogoutActions,
}
