import {
    loggedInAdminInfoActionConstants,
    LoggedInAdminInfoActions,
    loginActionConstant,
    LoginActions,
    logoutActionConstants,
    LogoutActions,
    MenuActions,
    userMenusActionConstant,
    weekdaysActionConstants,
    WeekdaysActions,
    ForgotPasswordActions
} from './src/common'
import {
    adminSetupActionConstants,
    AdminSetupActions,
    AppointmentDetailActions,
    appointmentDetailsConstants,
    dashboardDetailsActionsConstant,
    DashboardDetailsActions,
    DoctorSetupActions,
    doctorSetupConstants,
    DepartmentSetupActions,
    departmentSetupConstants,
    doctorDutyRosterActionConstants,
    DoctorDutyRosterActions,
    HospitalSetupActions,
    hospitalSetupConstants,
    ProfileSetupActions,
    profileSetupConstants,
    SpecializationSetupActions,
    specializationSetupConstants,
    QualificationSetupActions,
    qualificationSetupConstants,
    PatientDetailsActions,
    patientDetailsConstants
   
} from './src/admin-module'

export {
    adminSetupActionConstants,
    AdminSetupActions,
    AppointmentDetailActions,
    appointmentDetailsConstants,
    dashboardDetailsActionsConstant,
    DashboardDetailsActions,
    DoctorSetupActions,
    doctorSetupConstants,
    DepartmentSetupActions,
    departmentSetupConstants,
    doctorDutyRosterActionConstants,
    DoctorDutyRosterActions,
    HospitalSetupActions,
    hospitalSetupConstants,
    loginActionConstant,
    LoginActions,
    MenuActions,
    ProfileSetupActions,
    profileSetupConstants,
    SpecializationSetupActions,
    specializationSetupConstants,
    userMenusActionConstant,
    loggedInAdminInfoActionConstants,
    LoggedInAdminInfoActions,
    logoutActionConstants,
    LogoutActions,
    QualificationSetupActions,
    qualificationSetupConstants,
    weekdaysActionConstants,
    WeekdaysActions,
    PatientDetailsActions,
    patientDetailsConstants,
    ForgotPasswordActions
}
