export const ddrShiftWiseActionConstants = {
    DDR_CHECK_AVAILABILITY_PENDING: 'DDR-CHECK-AVAILABILITY-PENDING',
    DDR_CHECK_AVAILABILITY_SUCCESS: 'DDR-CHECK-AVAILABILITY-SUCCESS',
    DDR_CHECK_AVAILABILITY_ERROR: 'DDR-CHECK-AVAILABILITY-ERROR',
    CLEAR_DDR_CHECK_AVAILABILITY_MESSAGE: 'CLEAR-DDR-CHECK-AVAILABILITY-MESSAGE',
    SAVE_DDR_WEEKDAYS_PENDING: 'SAVE-DDR-WEEKDAYS-PENDING',
    SAVE_DDR_WEEKDAYS_SUCCESS: 'SAVE-DOCTOR-DUTY-ROSTER-WEEKDAYS-SUCCESS',
    SAVE_DDR_WEEKDAYS_ERROR: 'SAVE-DOCTOR-DUTY-ROSTER-WEEKDAYS-ERROR',
    CLEAR_DDR_WEEKDAYS_SAVE_MESSAGE: 'CLEAR-DDR-WEEKDAYS-SAVE-MESSAGE',
};
