export const weekdaysActionConstants = {
    FETCH_WEEK_DAYS_SUCCESS: "FETCH-WEEK-DAYS-SUCCESS",
    FETCH_WEEK_DAYS_ERROR: "FETCH-WEEK-DAYS-DATA-ERROR",
    FETCH_WEEK_DAYS_DATA_SUCCESS: "FETCH-WEEK-DAYS-DATA-SUCCESS",
    FETCH_WEEK_DAYS_DATA_ERROR: "FETCH-WEEK-DAYS-DATA-ERROR",
};
