export {default as Login} from './src/Login';
export {default as ClientLogin} from './src/ClientLogin';
export {default as CLayout} from './src/CLayout';
export {default as ConfirmDelete} from './src/DeleteRemarksModal';
export {default as CImageUploadAndCropModal} from './src/CImageUploadAndCrop';
export {default as NewPassword} from './src/CNewPassword';
export {default as CPasswordSaveForm} from './src/CPasswordSaveForm';
export {default as CEnglishDatePicker} from './src/CEnglishDatePicker';
export {default as CTimePicker} from './src/CTimePicker';
export {default as CConfirmationModal} from './src/CConfirmationModal' ;
export {default as CDateButtonPills} from './src/CDateButtonPills/CDateButtonPills';
export {default as CForgotPassword} from './src/CForgotPassword/CForgotPassword';
export {default as CCodeVerification} from './src/CCodeVerification/CCodeVerification';
export {default as CChangePasswordInForget} from './src/CChangePaswordInForget/CChangePasswordInForget';